tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "osx-cross/avr"
tap "px4/px4"
tap "universal-ctags/universal-ctags"
cask "java"
cask "xquartz"
brew "atool"
brew "avrdude"
brew "sqlite"
brew "python"
brew "awscli"
brew "cmake"
brew "ctags"
brew "dfu-programmer"
brew "elinks"
brew "elixir"
brew "exiftool"
brew "git"
brew "graphviz", args: ["with-librsvg", "with-pango"]
brew "grep"
brew "gzip"
brew "highlight"
brew "htop"
brew "libcaca"
brew "libyaml"
brew "lynx"
brew "macvim", args: ["with-override-system-vim"]
brew "mas"
brew "media-info"
brew "mlt"
brew "mongodb", restart_service: true
brew "mono"
brew "mysql", restart_service: true
brew "neovim"
brew "node"
brew "poppler"
brew "postgresql", restart_service: true
brew "postgis"
brew "ranger"
brew "rbenv"
brew "shpotify"
brew "tig"
brew "tmux"
brew "transmission"
brew "trash"
brew "w3m"
brew "watchman"
brew "weechat"
brew "yarn"
brew "zsh"
brew "zsh-completions"
brew "osx-cross/avr/avr-gcc"
brew "px4/px4/gcc-arm-none-eabi"
cask "alfred"
cask "boxer"
cask "dash"
cask "djview"
cask "dropbox"
cask "expo-xde"
cask "figma"
cask "fontforge"
cask "gfxcardstatus"
cask "gitkraken"
cask "goofy"
cask "haskell-platform"
cask "insomniax"
cask "karabiner-elements"
cask "knuff"
cask "licecap"
cask "mediainfo"
cask "ngrok"
cask "postico"
cask "postman"
cask "private-internet-access"
cask "sketch"
cask "spectacle"
cask "spotify"
cask "steam"
cask "sublime-text"
cask "torbrowser"
cask "transmission"
cask "vanilla"
cask "visual-studio-code"
cask "vlc"
cask "vox"
cask "homebrew/cask-drivers/qmk-toolbox"
cask "homebrew/cask-versions/iterm2-nightly"
cask "homebrew/cask-versions/safari-technology-preview"
mas "(13302)", id: InstallOS
mas "hisuite", id: 1232508288
mas "Shazam", id: 897118787
mas "The Unarchiver", id: 425424353
mas "WeChat", id: 836500024
